### ISSUE TITLE
Python 3 support

### ISSUE THREAD

**Issue by IvarsKarpics** [mxcube/BlissFramework#7]
Hi all,

Few weeks around there was a workaround to test if it is possible to use mxcube and python3. With a major help from @douglasbeniz the initial work was done and MXCuBE is compatible with python3.x. There will be coming more commits (also to HardwareRepository) and bug fixes. 

Cheers,
Ivars

**Comment by mguijarr** [comment]
Thanks a lot to @douglasbeniz :+1: and to you @IvarsKarpics this is really great news.

**Comment by hellmig** [comment]
HI Ivars,

Does this mean that the latest revision of the master branch is not compatible with Python 2.x any more?! 
Yesterday I tried to update our local beamline installation but the merge of the BlissFramework master branch crashed my setup because of a missing http.client module (and maybe other stuff ...) in Python 2.x.
In my opinion it would be useful to also introduce version tags in our submodules which would make it easier to find out the last stable commit for the submodules.

Generally, is there a plan to skip support for Python 2.x in the near future?

Best wishes,
Michael

**Comment by IvarsKarpics** [comment]
Hi @hellmig and others,

No there is no plan to skip python 2.x. The idea is to have a code compatible with both versions. In our case we will run mxcube with python 2.7, because our Tine library handles it.
I was trying to debug code as much as I can, but I can imagine that there is still some things missing. 
Which module it was?
Move to python3 is a major change and after a testing I will put a tag and release 2.2.1.
Please do not hesitate to send bug reports, open issues or make pull requests. 

cheers,
Ivars

**Comment by hellmig** [comment]
Hi Ivars,

The problem is in the bottle module which is used for the terminal server: the import of the http.client module fails in Python 2.x

M.

**Comment by IvarsKarpics** [comment]
Hi,

As I see in the code Qt4_startGUI terminal_server import is commented. About previous version startGUI I am not sure. Does somebody uses it? Actually what it is made for?
If it is used then there should be something is the style:
```python
import sys
 if sys.version_info < (3. 0):
     import jttplib as http_client
 else:
     import http.client as http_client 
```
And update code where it is necessary

**Comment by mguijarr** [comment]
Hello,
The terminal server was an attempt to have a live debugging console in order to inspect / solve a
running MXCuBE using a web browser.
It's something I started that I never really continued, however it works for what it is doing... But it
is not used by anyone to my knowledge.

**Comment by IvarsKarpics** [comment]
Hi,

Thanks for info @mguijarr . It is commented out in the code, so it should not cause any compatibility problems. Of course, if someone is willing to continue this, then there is no problem to work on this.

**Comment by IvarsKarpics** [comment]
There will be a presentation about python3 and mxcube on the next meetings.
Now I will close this
